name: Publish Inference image

on:
  push:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push inference image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Exit if commit was an automated version bump or tag push
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "Commit message: $COMMIT_MSG"
      
          if [[ "$COMMIT_MSG" =~ ^ci:\ version\ bump\ to\ v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Skipping workflow for version bump commit."
            exit 0
          fi
            
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "Skipping workflow for tag push."
            exit 0
          fi
          
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata for inference
        id: meta-inference
        uses: docker/metadata-action@v5
        with:
          images: cccalculator/clinicalcompetencycalculator-inference

      - name: Build and push inference Docker image
        id: inference-push
        uses: docker/build-push-action@v5
        with:
            context: ./python/infer
            file: ./python/infer/Dockerfile
            push: true
            tags: ${{ steps.meta-inference.outputs.tags }}
            labels: ${{ steps.meta-inference.outputs.labels }}
